name: Update Random Dev Quote

# Se ejecuta cada día a la medianoche UTC; puedes ajustar el cron a tu zona
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:    # Permite ejecutar el workflow manualmente

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update quote in README
        run: npm run update-quote

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: actualizar cita aleatoria"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
